### ISSUE TITLE
Caching Proxy for Slurm REST API

### ISSUE THREAD

**Issue by chrisdaaz** [lcrownover/prometheus-slurm-exporter#22]
Thank you for developing this! Since the Slurm REST API is required, do you recommend users setup a caching proxy for the Slurm REST API? The [Slurm REST API documentation states](https://slurm.schedmd.com/rest.html):

> Sites are strongly encouraged to setup a caching proxy between slurmrestd and clients to avoid having clients repeatedly call queries, causing usage to be higher than needed (and causing lock contention) on the controller.

We haven't used the Slurm REST API in our cluster before, so any setup advice from your experience would be appreciated!

**Comment by lcrownover** [comment]
Hey @chrisdaaz , thanks for pointing that out! If you expect **users** to hit slurmrestd, you probably want to set up a caching proxy because it does seem like queries to some APIs (jobs in particular) are pretty expensive, and you can't control what those crazy folks are doing 😉

This exporter, however, shouldn't require a proxy because you're in control of the [scrape interval](https://github.com/lcrownover/prometheus-slurm-exporter?tab=readme-ov-file#prometheus-server-scrape-config), and an interval of 30 seconds should be no sweat for slurm. In addition, this exporter is configured with an internal cache so it only makes one call to each of the required endpoints during a gather operation.

Feel free to ask if you have any other questions!

**Comment by chrisdaaz** [comment]
Thanks, @lcrownover! I'll report back if we're able to give this a try.
