### ISSUE TITLE
Fair share metrics are not working correctly

### ISSUE THREAD

**Issue by rjohnson-ha** [lcrownover/prometheus-slurm-exporter#8]
The exporter is repeatedly printing errors like this:

Sep 27 13:19:30 slurm-export prometheus-slurm-exporter[1895]: time=2024-09-27T13:19:30.852-05:00 level=ERROR msg="failed to unmarshal shares response for fair share metrics" error="failed to unmarshall shares response data: invalid character 'i' looking for beginning of value"

and as a result, the fair share section of the grafana dashboard is empty.  I'm running slurm 23.11.6 if that matters.

**Comment by rjohnson-ha** [comment]
Reading through the code, it looks like you are working around getting "Infinity" back as a value for level in the response to the shares API call.  In my environment, it is coming back with "inf" instead and that is likely why it's failing for me.

Any chance of patching that?

**Comment by lcrownover** [comment]
Thanks for the heads up!

https://github.com/lcrownover/prometheus-slurm-exporter/commit/645ca71018170688222b83f2ebed28b4830d3718

New release:

https://github.com/lcrownover/prometheus-slurm-exporter/releases/tag/v1.0.6

**Comment by rjohnson-ha** [comment]
Looks like the calls are being returned slightly differently depending on the technique / library used to make the REST call.  

I'm getting this now:

Sep 27 18:22:49 slurm-export prometheus-slurm-exporter[2132]: time=2024-09-27T18:22:49.413-05:00 level=ERROR msg="failed to unmarshal shares response for fair share metrics" error="failed to unmarshall shares response data: json: unknown field \"1.7976931348623157e+308inite\""

which looks like in your case it was returning "infinite" instead of "inf".

**Comment by lcrownover** [comment]
Ahh, bummer. Yeah I'm working around the slurm bug specified in the comments. Should be fixed in their API version 42, but that's only available in 24.11, so I have that ugly hack 😀 

I'll take a closer look at this tomorrow!

**Comment by lcrownover** [comment]
Didn't know that I guess typing "fix <issue number>" automatically closes the issue. I'll reopen this one to make sure it's working for you in 1.0.7: https://github.com/lcrownover/prometheus-slurm-exporter/releases/tag/v1.0.7

**Comment by lcrownover** [comment]
I was writing some more tests against the limited sample data from SchedMD and found some other cases where the key is "infinite" instead of the value, so it was getting incorrectly replaced by the string replacement. I've adjusted the replace so it targets the string like `: Infinity` and `: Inf` so it should only pick up the values. 

https://github.com/lcrownover/prometheus-slurm-exporter/blob/main/internal/api/unmarshalers_2405.go#L56

Since I'm leveraging their generated types, I don't _think_ I can easily write a custom unmarshaler... so this is the best I can do right now. I think it should work. Let me know 😊

Release 1.0.9: https://github.com/lcrownover/prometheus-slurm-exporter/releases/tag/v1.0.9

**Comment by rjohnson-ha** [comment]
I was playing with this a little yesterday and noticed the same thing you are describing.

I'm trying 1.0.9 and it is still not working, but I think the commit for the ": inf" maybe didn't make it into that release?

**Comment by lcrownover** [comment]
Ha, you're right. I did a large refactor on Saturday night to make navigating the code a little easier and I moved this parsing logic into the unmarshal function as it seemed like a better place to put it. I did not remember to put it into the 2311 unmarshaler (my bad). 

In v1.0.10 I've correctly applied the Infinity parsing on the 23.11 code and added Infinity strings to the test data to make sure it gets handled correctly.

https://github.com/lcrownover/prometheus-slurm-exporter/releases/tag/v1.0.10

**Comment by rjohnson-ha** [comment]
I just tried 1.0.10 and it's doing the same thing still.

**Comment by lcrownover** [comment]
Can you please do the following:

- Run `prometheus-slurm-exporter -v` and verify the version is 1.0.10

- Give me the exact output of the error

- Give me a snippet of the response data from your scheduler. You can get this with:

  ```bash
  export SLURM_TOKEN="your token"
  curl http://headnode.domain.org:6820/slurm/v0.0.40/shares -H "X-SLURM-USER-NAME: root" -H "X-SLURM-USER-TOKEN: $SLURM_TOKEN"
  ```

  A good snippet might be `| grep -i infinity -C10`

**Comment by rjohnson-ha** [comment]
Sure.  See attached for a curl snippet.  I cut it to a handful of "| grep -i inf -C10" with user, group, and cluster names redacted.  Grep'ing for "infinity" came back empty.

[root@slurm-export ~]# /usr/local/bin/prometheus-slurm-exporter -v
2024/09/30 18:46:02 Starting Prometheus Slurm Exporter 1.0.10
1.0.10

Sep 30 18:46:31 slurm-export prometheus-slurm-exporter[4123]: time=2024-09-30T18:46:31.445-05:00 level=ERROR msg="failed to unmarshal shares response for fair share metrics" error="failed to unmarshall shares response data: json: unknown field \"1.7976931348623157e+308inite\""
Sep 30 18:46:46 slurm-export prometheus-slurm-exporter[4123]: time=2024-09-30T18:46:46.353-05:00 level=ERROR msg="failed to unmarshal shares response for fair share metrics" error="failed to unmarshall shares response data: json: unknown field \"1.7976931348623157e+308inite\""

[debug.txt](https://github.com/user-attachments/files/17197523/debug.txt)

**Comment by lcrownover** [comment]
That's awesome, thank you for the input. I'm crossing my fingers that this is finally fixed in https://github.com/lcrownover/prometheus-slurm-exporter/pull/18/commits/14d750211ebdbea26a975ab0b35caaf577a2b82f, I'll admit that, like the last issue, I failed to remove the old code from the 23.11 version when working on it for 24.05. It's a bummer to have multiple versions for each SLURM version, but I haven't been able to think of a better way to provide conditional support.

I'll get a release uploaded tomorrow morning!

Sorry for so much back and forth, growing pains on this new tool :)

**Comment by lcrownover** [comment]
I'm pretty confident this is fixed in https://github.com/lcrownover/prometheus-slurm-exporter/releases/tag/v1.0.11

**Comment by rjohnson-ha** [comment]
That did the trick!

Thanks for working with me on this issue...

**Comment by lcrownover** [comment]
Awesome! Happy to help 😊 thanks for sticking with it!
